import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST() {
  // Create users
  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: "admin@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Administrador",
        email: "admin@igc.sp.gov.br",
        role: "ADMIN",
        department: "CATDT",
      },
    }),
    prisma.user.upsert({
      where: { email: "gerente@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Carlos Silva",
        email: "gerente@igc.sp.gov.br",
        role: "GERENTE",
        department: "CATDT",
      },
    }),
    prisma.user.upsert({
      where: { email: "diretor@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Roberto Santos",
        email: "diretor@igc.sp.gov.br",
        role: "DIRETOR",
      },
    }),
    prisma.user.upsert({
      where: { email: "thiago@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Thiago Barrocal",
        email: "thiago@igc.sp.gov.br",
        role: "TECNICO",
        department: "CATDT",
      },
    }),
    prisma.user.upsert({
      where: { email: "ana@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Ana Oliveira",
        email: "ana@igc.sp.gov.br",
        role: "TECNICO",
        department: "CATDT",
      },
    }),
    prisma.user.upsert({
      where: { email: "marcos@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Marcos Pereira",
        email: "marcos@igc.sp.gov.br",
        role: "CONFERENTE",
        department: "CATDT",
      },
    }),
    prisma.user.upsert({
      where: { email: "sdtc@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Maria SDTC",
        email: "sdtc@igc.sp.gov.br",
        role: "SDTC",
        department: "SDTC",
      },
    }),
    prisma.user.upsert({
      where: { email: "pedro@igc.sp.gov.br" },
      update: {},
      create: {
        name: "Pedro Costa",
        email: "pedro@igc.sp.gov.br",
        role: "TECNICO",
        department: "CG",
      },
    }),
  ]);

  // Create sample processes
  const sampleProcesses = [
    {
      ordem: 1,
      anoEntrada: 2026,
      tipoServico: "Certidao",
      expediente: "DDD_013.000034472026-66",
      dtAbertoSei: new Date("2026-01-15"),
      tipo: "Comum-CPF",
      interessado: "Jose da Silva",
      email: "jose@email.com",
      municipio: "Sao Paulo",
      ra: "RA-1",
      situacao: "analise_tecnica",
      tecnicoRespId: users[3].id,
      base: "10k",
      departamento: "CATDT",
      criadoPorId: users[6].id,
    },
    {
      ordem: 2,
      anoEntrada: 2026,
      tipoServico: "Certidao",
      expediente: "DDD_013.000035002026-12",
      dtAbertoSei: new Date("2026-01-20"),
      tipo: "idoso",
      interessado: "Maria Aparecida",
      email: "maria@email.com",
      municipio: "Campinas",
      situacao: "conferencia",
      tecnicoRespId: users[4].id,
      tecnicoConfId: users[5].id,
      base: "50k",
      departamento: "CATDT",
      criadoPorId: users[6].id,
    },
    {
      ordem: 3,
      anoEntrada: 2026,
      tipoServico: "Drenagem",
      expediente: "DDD_013.000036002026-33",
      dtAbertoSei: new Date("2026-02-01"),
      tipo: "Orgao-Publico",
      interessado: "Prefeitura de Santos",
      municipio: "Santos",
      situacao: "entrada_sdtc",
      criadoPorId: users[6].id,
    },
    {
      ordem: 4,
      anoEntrada: 2026,
      tipoServico: "Parecer",
      expediente: "DDD_013.000037002026-44",
      dtAbertoSei: new Date("2026-02-10"),
      tipo: "Justica",
      interessado: "Tribunal de Justica SP",
      municipio: "Sao Paulo",
      situacao: "assinatura_gerente",
      tecnicoRespId: users[3].id,
      dtAssTecnico: new Date("2026-03-01"),
      base: "10k",
      departamento: "CATDT",
      criadoPorId: users[6].id,
    },
    {
      ordem: 5,
      anoEntrada: 2026,
      tipoServico: "Certidao",
      expediente: "DDD_013.000038002026-55",
      dtAbertoSei: new Date("2026-02-15"),
      tipo: "Comum-CNPJ",
      interessado: "Construtora ABC Ltda",
      email: "contato@abc.com.br",
      municipio: "Guarulhos",
      situacao: "distribuicao_gdat",
      criadoPorId: users[6].id,
    },
    {
      ordem: 6,
      anoEntrada: 2026,
      tipoServico: "Tracado de Divisa em Planta",
      dtAbertoSei: new Date("2026-03-01"),
      tipo: "Comum-CPF",
      interessado: "Carlos Mendes",
      municipio: "Sorocaba",
      situacao: "assinatura_diretor",
      tecnicoRespId: users[4].id,
      dtAssTecnico: new Date("2026-03-15"),
      dtAssGerente: new Date("2026-03-20"),
      departamento: "CATDT",
      criadoPorId: users[6].id,
    },
    {
      ordem: 7,
      anoEntrada: 2026,
      tipoServico: "Certidao",
      dtAbertoSei: new Date("2026-03-10"),
      tipo: "Comum-CPF",
      interessado: "Fernanda Lima",
      municipio: "Ribeirao Preto",
      situacao: "upload_sei",
      tecnicoRespId: users[3].id,
      dtAssTecnico: new Date("2026-04-01"),
      dtAssGerente: new Date("2026-04-05"),
      dtAssDiretor: new Date("2026-04-10"),
      departamento: "CATDT",
      criadoPorId: users[6].id,
    },
    {
      ordem: 8,
      anoEntrada: 2025,
      tipoServico: "Certidao",
      expediente: "DDD_013.000001002025-01",
      dtAbertoSei: new Date("2025-06-15"),
      tipo: "Comum-CPF",
      interessado: "Pedro Almeida",
      municipio: "Bauru",
      situacao: "finalizado",
      tecnicoRespId: users[7].id,
      dtAssTecnico: new Date("2025-08-01"),
      dtAssGerente: new Date("2025-08-05"),
      dtAssDiretor: new Date("2025-08-10"),
      dtUpadoSei: new Date("2025-08-15"),
      numeroSaidaIGC: "IGC-2025-001",
      departamento: "CG",
      criadoPorId: users[6].id,
    },
    {
      ordem: 9,
      anoEntrada: 2026,
      tipoServico: "Certidao",
      dtAbertoSei: new Date("2026-01-25"),
      tipo: "Comum-CPF",
      interessado: "Ricardo Souza",
      municipio: "Osasco",
      situacao: "sobrestado",
      dtInicioSobrestado: new Date("2026-02-20"),
      tecnicoRespId: users[4].id,
      departamento: "CATDT",
      criadoPorId: users[6].id,
    },
    {
      ordem: 10,
      anoEntrada: 2026,
      tipoServico: "Informacao Tecnica",
      dtAbertoSei: new Date("2026-03-20"),
      tipo: "Orgao-Publico",
      interessado: "SABESP",
      municipio: "Sao Paulo",
      situacao: "analise_tecnica",
      tecnicoRespId: users[7].id,
      base: "MDT 2023",
      departamento: "CG",
      criadoPorId: users[6].id,
    },
  ];

  const existingCount = await prisma.process.count();
  if (existingCount === 0) {
    for (const proc of sampleProcesses) {
      await prisma.process.create({ data: proc });
    }
  }

  return NextResponse.json({
    message: "Seed completed",
    users: users.length,
    processes: existingCount === 0 ? sampleProcesses.length : 0,
  });
}
