-- Campos legados detectados automaticamente
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "numeroSaidaIGC" TEXT;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "processes" TEXT;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "servicoTecCampo" DOUBLE PRECISION;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "servicoTecGabinete" DOUBLE PRECISION;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "taxaAbertura" DOUBLE PRECISION;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "taxaVistoria" DOUBLE PRECISION;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "total" TEXT;
ALTER TABLE "Process" ADD COLUMN IF NOT EXISTS "users" TEXT;
